# Generated by Django 6.0.3 on 2026-04-11 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0007_clase_add_constraints_and_default'),
        ('evaluaciones', '0002_intentoevaluacion_respuestas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo', models.CharField(choices=[('clase_deadline', 'Plazo de Clase'), ('evaluacion_deadline', 'Plazo de Evaluación'), ('curso_start', 'Inicio de Curso'), ('curso_end', 'Fin de Curso'), ('evento_general', 'Evento General')], default='evento_general', max_length=25)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('color', models.CharField(default='#6366f1', help_text='Color hex, ej: #6366f1', max_length=7)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='cursos.curso')),
                ('evaluacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_calendario', to='evaluaciones.evaluacion')),
            ],
            options={
                'verbose_name': 'Evento de Calendario',
                'verbose_name_plural': 'Eventos de Calendario',
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
