# Generated by Django 6.0.3 on 2026-04-22 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        ('cursos', '0008_clasecompletado_cursos_clas_usuario_b17fef_idx_and_more'),
        ('evaluaciones', '0006_intentoevaluacion_evaluacione_usuario_f41a07_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventocalendario',
            index=models.Index(fields=['fecha_inicio', 'fecha_fin'], name='calendario__fecha_i_7e3f1a_idx'),
        ),
    ]
