# Generated by Django 6.0.3 on 2026-04-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentoevaluacion',
            name='respuestas',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
