# Generated by Django 6.0.3 on 2026-04-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_intentoevaluacion_respuestas'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='max_intentos',
            field=models.IntegerField(default=0, help_text='0 = sin límite'),
        ),
    ]
