# Generated by Django 6.0.3 on 2026-04-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_evaluacion_max_intentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='duracion_minutos',
            field=models.IntegerField(blank=True, help_text='Minutos, vacío = sin límite', null=True),
        ),
        migrations.AddField(
            model_name='intentoevaluacion',
            name='hora_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
