# Generated by Django 6.0.3 on 2026-04-11 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_clase_add_constraints_and_default'),
        ('evaluaciones', '0004_evaluacion_duracion_minutos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='preguntas_por_intento',
            field=models.IntegerField(blank=True, help_text='Aleatorizar N preguntas del banco', null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluaciones.evaluacion'),
        ),
        migrations.CreateModel(
            name='BancoPreguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('es_publico', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos_creados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bancos_preguntas', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Banco de Preguntas',
                'verbose_name_plural': 'Bancos de Preguntas',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='evaluaciones.bancopreguntas'),
        ),
    ]
