# Generated by Django 6.0.3 on 2026-04-22 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_evaluacion_preguntas_por_intento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='intentoevaluacion',
            index=models.Index(fields=['usuario', 'evaluacion'], name='evaluacione_usuario_f41a07_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoevaluacion',
            index=models.Index(fields=['evaluacion', '-fecha_intento'], name='evaluacione_evaluac_8c0dc2_idx'),
        ),
    ]
