# Generated by Django 6.0.3 on 2026-04-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha límite'),
        ),
    ]
