# Generated by Django 6.0.3 on 2026-04-10 17:50

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_categoria_curso_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField(verbose_name='Contenido de la clase')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de la clase en el curso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ClaseCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completados', to='cursos.clase')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_completadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clase Completada',
                'verbose_name_plural': 'Clases Completadas',
                'unique_together': {('usuario', 'clase')},
            },
        ),
    ]
