# Generated by Django 6.0.3 on 2026-04-22 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_clase_add_constraints_and_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clasecompletado',
            index=models.Index(fields=['usuario', 'clase'], name='cursos_clas_usuario_b17fef_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='cursos_curs_estado_6d0143_idx'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['docente_creador'], name='cursos_curs_docente_80cfba_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['usuario', 'estado'], name='cursos_insc_usuario_84d271_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['curso', 'estado'], name='cursos_insc_curso_i_8052fe_idx'),
        ),
        migrations.AddIndex(
            model_name='inscripcioncurso',
            index=models.Index(fields=['fecha_asignacion'], name='cursos_insc_fecha_a_4fc35d_idx'),
        ),
    ]
