# Generated by Django 6.0.3 on 2026-04-22 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_clasecompletado_cursos_clas_usuario_b17fef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveIntegerField(default=0)),
                ('clases_completadas', models.PositiveIntegerField(default=0)),
                ('total_clases', models.PositiveIntegerField(default=0)),
                ('evaluaciones_aprobadas', models.PositiveIntegerField(default=0)),
                ('total_evaluaciones', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='cursos.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Curso',
                'verbose_name_plural': 'Progresos de Cursos',
                'indexes': [models.Index(fields=['usuario', 'curso'], name='cursos_prog_usuario_519edd_idx'), models.Index(fields=['porcentaje'], name='cursos_prog_porcent_841843_idx')],
                'unique_together': {('usuario', 'curso')},
            },
        ),
    ]
