# Generated by Django 6.0.3 on 2026-04-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_progresocurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificado_activo',
            field=models.BooleanField(default=True, help_text='Este curso emite certificado al completarse'),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_porcentaje_minimo_clases',
            field=models.PositiveIntegerField(default=100, help_text='Porcentaje mínimo de clases requeridas (0-100)'),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_requiere_clases',
            field=models.BooleanField(default=True, help_text='Requiere completar todas las clases para obtener el certificado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_requiere_evaluaciones',
            field=models.BooleanField(default=True, help_text='Requiere aprobar todas las evaluaciones para obtener el certificado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='certificado_vigencia_meses',
            field=models.PositiveIntegerField(default=0, help_text='Meses de vigencia del certificado. 0 = sin vencimiento'),
        ),
    ]
