# Generated by Django 6.0.3 on 2026-04-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_curso_certificado_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video URL'), ('video_file', 'Video (archivo)'), ('office', 'Documento Office')], max_length=20),
        ),
    ]
