# Generated by Django 6.0.3 on 2026-03-26 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_verificacion', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
            },
        ),
    ]
