# Generated by Django 6.0.3 on 2026-04-22 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_certificado_estado'),
        ('cursos', '0008_clasecompletado_cursos_clas_usuario_b17fef_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='certificado',
            index=models.Index(fields=['estado'], name='certificado_estado_02805c_idx'),
        ),
    ]
