# Generated by Django 6.0.3 on 2026-04-23 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0005_certificado_certificado_estado_02805c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento del certificado. Nulo = sin vencimiento', null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='motivo_revocacion',
            field=models.TextField(blank=True, help_text='Motivo de la revocación del certificado', null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revocado', 'Revocado')], default='pendiente', max_length=20),
        ),
    ]
