# Generated by Django 6.0.3 on 2026-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0006_certificado_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revocado', 'Revocado'), ('expirado', 'Expirado')], default='pendiente', max_length=20),
        ),
    ]
