# Generated by Django 6.0.3 on 2026-04-22 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_recordatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('curso_completado', 'Curso completado'), ('evaluacion_intento', 'Intento de evaluación'), ('certificado_aprobado', 'Certificado aprobado'), ('usuario_creado', 'Usuario creado'), ('inscripcion_creada', 'Inscripción creada')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=50)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['usuario', '-fecha'], name='usuarios_au_usuario_dba757_idx'), models.Index(fields=['accion', '-fecha'], name='usuarios_au_accion_e37942_idx')],
            },
        ),
    ]
